### ISSUE TITLE
XboxController not found!

### ISSUE THREAD

**Issue by Walid-khaled** [RoboDK/Plug-In-Interface#59]
Hello! 
  I am trying to jog a real robot using xbox/keyboard but I am struggling with that due to a delay in sending the robot commands and receiving the robot state which cause the robot a jerky motion. Can you provide the code for controlling the robot using the Xbox?

**Comment by sambertrdk** [comment]
You can find the source code of the Game Controller here:
https://github.com/RoboDK/Plug-In-Interface/tree/master/PluginAppLoader/Apps/GameController
