### ISSUE TITLE
development environment setup

### ISSUE THREAD

**Issue by sancelot** [RoboDK/Plug-In-Interface#8]
Hi, 
I had to move my development environment from win7 to win10.

Unfortunately I don't manage to generate usable dll in this new environment.

In robodk,  my plugin fails loading as follow :

09:36:45.315 (+9074 ms): Debug: Loading plugin:  "e:/RoboDK/bin/plugins/PluginNumalliance.dll"
09:36:45.326 (+11 ms): Debug: Failed to load plugin:  "Failed to extract plugin meta data from 'E:/RoboDK/bin/plugins/PluginNumalliance.dll'"

The one generated on win7 system always works.

My Target is Robodk 5.1.1
I used  qt creator 4.11 
Qt 5.13
MSVC 2017

**Comment by RoboDK** [comment]
We recently updated the plugin interface. You should make sure to use the header files appropriate for your version. For example, RoboDK 5.1.1 was released with a new plugin interface in September 2020. You can find the list of updates here:
https://robodk.com/whatsnew

You should then use the robodk_interface folder available at that time or before the next plugin interface modification:
https://github.com/RoboDK/Plug-In-Interface/tree/cfbc05c3c0f3f94e15075b3927ab0a2295354706/robodk_interface

**Comment by RoboDK** [comment]
For the plugin to properly compile and work without strange crashes you should verify the following:
1. Update the header files (.h) from the robodk_interface folder.
2. Update RoboDK to the latest version (version RoboDK 5.3).
3. Update Qt (version 5.15.x).
